# Generated by Django 3.2.8 on 2021-10-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blod_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
