# Generated by Django 3.2.8 on 2021-10-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blod_data',
            new_name='blog_data',
        ),
    ]
