# Generated by Django 3.2.8 on 2021-10-27 09:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
