# Generated by Django 3.2.8 on 2021-10-27 10:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_blog_data_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
