# Generated by Django 3.2.8 on 2021-11-01 07:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_data',
            name='cover_image',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
