# Generated by Django 3.2.8 on 2021-11-02 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_blog_data_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_data',
            options={'ordering': ('-published_date',)},
        ),
        migrations.AddField(
            model_name='blog_data',
            name='created_created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_data',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='blog_data',
            name='updated_create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog_data',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
