# Generated by Django 3.2.8 on 2021-11-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_alter_blog_data_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='category',
            field=models.ForeignKey(default='7', on_delete=django.db.models.deletion.SET_DEFAULT, to='blogapp.category'),
        ),
    ]
