# Generated by Django 3.2.8 on 2021-11-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_auto_20211111_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_data',
            name='views',
        ),
        migrations.CreateModel(
            name='no_views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog_data')),
            ],
        ),
    ]
